server:
  port: 8761
spring:
  application: 
    name: credit-eureka-server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false         #开发测试环境关闭自我保护，上线时需要开启
    eviction-interval-timer-in-ms: 5000  #client下线通知server的频率
